# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/devonf-motcamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),devonf-motcamera)

endif
